language: php


php:
  - 5.6
  - 7.1
  - 7.2
  - 7.3

services:
  - mysql
  
before_install:
   # Prepare MySQL schema
  - mysql < ./application/schema/schema.sql
  - mysql -e "SET PASSWORD = PASSWORD('travisci');"

script:
  - composer update
  - cd application/tests
  - ../../vendor/bin/phpunit -c phpunit.xml